version: '3.8'

services:
  proxysql:
    image: proxysql/proxysql
    container_name: proxysql
    ports:
      - "6033:6033"  # untuk koneksi aplikasi
      - "6032:6032"  # untuk admin interface
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro
    restart: unless-stopped
    networks:
      - appnet

  pemweb:
    build: ./php
    image: pemweb_php:latest
    container_name: pemweb
    hostname: "pemweb"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - proxysql
    networks:
      - appnet

  nginx_pemweb:
    build: ./nginx
    image: nginx_pemweb:latest
    container_name: nginx_pemweb
    hostname: "nginx_pemweb"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pemweb
    networks:
      - appnet

networks:
  appnet:
